#!/usr/bin/perl 
#===============================================================================
#
#         FILE:  |FILENAME|
#
#        USAGE:  ./|FILENAME| 
#
#  DESCRIPTION:  |CURSOR|
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  |AUTHOR| (|AUTHORREF|), <|EMAIL|>
#      COMPANY:  |COMPANY|
#      VERSION:  1.0
#      CREATED:  |DATE|
#     REVISION:  ---
#===============================================================================

use strict;
use warnings;
use Getopt::Long;

my $usage = <<EOU;
Usage:
    $0 --db DSN
    $0 --action [hide|show]
EOU

my %opts;
GetOptions(\%opts, "db=s", "action=s") or die $usage;

